#!/bin/bash
echo "Starting GameServer XML files validation ..."
DATAPATH="data/static_data"
xmllint --noout --schema $DATAPATH/bind_points/bind_points.xsd $DATAPATH/bind_points/bind_points.xml
xmllint --noout --schema $DATAPATH/cube_expander/cube_expander.xsd $DATAPATH/cube_expander/cube_expander.xml
xmllint --noout --schema $DATAPATH/gatherables/gatherable_templates.xsd $DATAPATH/gatherables/gatherable_templates.xml
xmllint --noout --schema $DATAPATH/goodslists/goodslists.xsd $DATAPATH/goodslists/goodslists.xml
xmllint --noout --schema $DATAPATH/item_sets/item_sets.xsd $DATAPATH/item_sets/item_sets.xml
xmllint --noout --schema $DATAPATH/items/item_templates.xsd $DATAPATH/items/item_templates.xml
xmllint --noout --schema $DATAPATH/npcs/npcs.xsd $DATAPATH/npcs/npc_templates.xml
xmllint --noout --schema $DATAPATH/portals/portal_templates.xsd $DATAPATH/portals/portal_templates.xml
xmllint --noout --schema $DATAPATH/quest_data/quest_data.xsd $DATAPATH/quest_data/quest_data.xml
xmllint --noout --schema $DATAPATH/quest_script_data/quest_script_data.xsd $DATAPATH/quest_script_data/altgard.xml
xmllint --noout --schema $DATAPATH/quest_script_data/quest_script_data.xsd $DATAPATH/quest_script_data/beluslan.xml
xmllint --noout --schema $DATAPATH/quest_script_data/quest_script_data.xsd $DATAPATH/quest_script_data/brusthonin.xml
xmllint --noout --schema $DATAPATH/quest_script_data/quest_script_data.xsd $DATAPATH/quest_script_data/eltnen.xml
xmllint --noout --schema $DATAPATH/quest_script_data/quest_script_data.xsd $DATAPATH/quest_script_data/heiron.xml
xmllint --noout --schema $DATAPATH/quest_script_data/quest_script_data.xsd $DATAPATH/quest_script_data/ishalgen.xml
xmllint --noout --schema $DATAPATH/quest_script_data/quest_script_data.xsd $DATAPATH/quest_script_data/morheim.xml
xmllint --noout --schema $DATAPATH/quest_script_data/quest_script_data.xsd $DATAPATH/quest_script_data/pandaemonium.xml
xmllint --noout --schema $DATAPATH/quest_script_data/quest_script_data.xsd $DATAPATH/quest_script_data/poeta.xml
xmllint --noout --schema $DATAPATH/quest_script_data/quest_script_data.xsd $DATAPATH/quest_script_data/reshanta.xml
xmllint --noout --schema $DATAPATH/quest_script_data/quest_script_data.xsd $DATAPATH/quest_script_data/sanctum.xml
xmllint --noout --schema $DATAPATH/quest_script_data/quest_script_data.xsd $DATAPATH/quest_script_data/theobomos.xml
xmllint --noout --schema $DATAPATH/quest_script_data/quest_script_data.xsd $DATAPATH/quest_script_data/verteron.xml
xmllint --noout --schema $DATAPATH/quest_script_data/quest_script_data.xsd $DATAPATH/quest_script_data/work_order.xml
xmllint --noout --schema $DATAPATH/recipe/recipe_templates.xsd $DATAPATH/recipe/recipe_templates.xml
xmllint --noout --schema $DATAPATH/skill_tree/skill_tree.xsd $DATAPATH/skill_tree/skill_tree.xml
xmllint --noout --schema $DATAPATH/skill_tree/skill_tree.xsd $DATAPATH/skill_tree/craft_skill_tree.xml
xmllint --noout --schema $DATAPATH/skills/skills.xsd $DATAPATH/skills/skill_templates.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Gather/210010000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Gather/210020000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Gather/210030000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Gather/210040000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Gather/210060000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Gather/220010000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Gather/220020000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Gather/220030000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Gather/220040000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Gather/220050000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Gather/400010000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Instances/300030000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Instances/300040000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Instances/320050000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Instances/320100000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Monsters/210010000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Monsters/210020000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Monsters/210030000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Monsters/210040000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Monsters/210060000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Monsters/220010000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Monsters/220020000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Monsters/220030000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Monsters/220040000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Monsters/220050000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Monsters/400010000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Npcs/110010000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Npcs/120010000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Npcs/210010000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Npcs/210020000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Npcs/210030000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Npcs/210040000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Npcs/210060000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Npcs/220010000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Npcs/220020000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Npcs/220030000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Npcs/220040000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Npcs/220050000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Npcs/310010000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Npcs/310020000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Npcs/310040000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Npcs/320020000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Npcs/320040000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Npcs/320050000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Npcs/320060000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Npcs/400010000.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/Rifts/rifts.xml
xmllint --noout --schema $DATAPATH/spawns/spawns.xsd $DATAPATH/spawns/StaticObjects/statics.xml
xmllint --noout --schema $DATAPATH/tribe/tribe_relations.xsd $DATAPATH/tribe/tribe_relations.xml
xmllint --noout --schema $DATAPATH/warehouse_expander/warehouse_expander.xsd $DATAPATH/warehouse_expander/warehouse_expander.xml
xmllint --noout --schema $DATAPATH/zones/zones.xsd $DATAPATH/zones/zones_110010000.xml
xmllint --noout --schema $DATAPATH/zones/zones.xsd $DATAPATH/zones/zones_210010000.xml
xmllint --noout --schema $DATAPATH/zones/zones.xsd $DATAPATH/zones/zones_210020000.xml
xmllint --noout --schema $DATAPATH/zones/zones.xsd $DATAPATH/zones/zones_210030000.xml
xmllint --noout --schema $DATAPATH/zones/zones.xsd $DATAPATH/zones/zones_210040000.xml
xmllint --noout --schema $DATAPATH/zones/zones.xsd $DATAPATH/zones/zones_220010000.xml
xmllint --noout --schema $DATAPATH/zones/zones.xsd $DATAPATH/zones/zones_220030000.xml
xmllint --noout --schema $DATAPATH/npc_teleporter.xsd $DATAPATH/npc_teleporter.xml
xmllint --noout --schema $DATAPATH/npc_trade_list.xsd $DATAPATH/npc_trade_list.xml
xmllint --noout --schema $DATAPATH/npc_walker.xsd $DATAPATH/npc_walker.xml
xmllint --noout --schema $DATAPATH/player_experience_table.xsd $DATAPATH/player_experience_table.xml
xmllint --noout --schema $DATAPATH/player_initial_data.xsd $DATAPATH/player_initial_data.xml
xmllint --noout --schema $DATAPATH/player_titles.xsd $DATAPATH/player_titles.xml
xmllint --noout --schema $DATAPATH/static_data.xsd $DATAPATH/static_data.xml
xmllint --noout --schema $DATAPATH/teleport_location.xsd $DATAPATH/teleport_location.xml
xmllint --noout --schema $DATAPATH/world_maps.xsd $DATAPATH/world_maps.xml
xmllint --noout --schema $DATAPATH/pet_skills/pet_skills.xsd $DATAPATH/pet_skills/pet_skills.xml
